### ISSUE TITLE
Program crash when trying to create new map

### ISSUE THREAD

**Issue by heyjude42** [R-T-B/TimberbornTerrainGenerator#1]
v0.2.4.1-9edd51d-xsw
Win32Exception: ApplicationName='C:\Users\User\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Timberborn\profiles\Default\BepInEx\plugins\RTB-TimberbornTerrainGenerator/dist/terrainGenerator.exe', CommandLine='128 128', CurrentDirectory='C:\Users\User\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Timberborn\profiles\Default\BepInEx\plugins\RTB-TimberbornTerrainGenerator/dist/', Native error= The system cannot find the file specified.

**Comment by heyjude42** [comment]
Mod was installed with Thunderstore mod manager in the usual way. Other installed mods are working.

**Comment by R-T-B** [comment]
Thanks for the report.  This is a pretty major issue I have missed!  I will look into this as soon as I am home (1-2 hours).  I have only tested manual installs.  I'm sure it's fixable though.

**Comment by R-T-B** [comment]
v0.3.5 fixes this.  Uploaded now. Thank you very much for the feedback/report! :)

**Comment by heyjude42** [comment]
Awesome - works great now, tyvm - appreciate the super fast fix :)
